name: Check & Test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test-server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - run: cargo +stable build --all-targets
      - run: cargo +stable test
